name: encode-and-commit
on: [push]

jobs:
  encode:
    runs-on: ubuntu-latest
    name: Encode
    steps:
      - uses: actions/checkout@v3
      - name: Encode
        uses: adawesomeguy/w3strings-action@v1.1
        with:
          csv-path: 'strings/en.w3strings.csv'
          id-space: 5018
          out-dir: 'strings'
          language: 'en'
        # if any of the strings are updated it will stage the commits and commit them
      - uses: endbug/add-and-commit@v8
        with:
            default_author: github_actions
            message: '[CI] Update W3Strings'
